// One-off seed generator for the platform demo data.
// Mirrors lib/seed.ts (houses, KPIs) and the deterministic generator in
// lib/mock-scores.ts so the seeded DB matches the mock fallback exactly.
// Run: node scripts/gen-seed.mjs > supabase/seed.sql
import { writeFileSync } from 'node:fs';

const HOUSES = [
  { slug: 'maseeh', name: 'Maseeh', type: 'residential' },
  { slug: 'baker', name: 'Baker', type: 'residential' },
  { slug: 'mccormick', name: 'McCormick', type: 'residential' },
  { slug: 'next', name: 'Next', type: 'residential' },
  { slug: 'simmons', name: 'Simmons', type: 'residential' },
  { slug: 'new-vassar', name: 'New Vassar', type: 'residential' },
  { slug: 'retail', name: 'Retail', type: 'cluster' },
];

// id, category, name, weightWithinCategory, signal_source — order matches seed.ts
const KPIS = [
  ['menu_compliance', 'nutrition_programming', 'Menu Compliance / BITE Standards', 50, 'Café Manager Menu Page'],
  ['special_diet_allergen', 'nutrition_programming', 'Special Diet & Allergen Execution', 50, 'Café Manager Menu Page'],
  ['food_cost_vs_budget', 'financial_performance', 'Food Cost vs Budget', 20, 'FoodCost Visualization'],
  ['labor_cost_vs_budget', 'financial_performance', 'Labor Cost vs Budget', 20, 'FY26 Labor Hours vs Budgeted'],
  ['cost_per_meal', 'financial_performance', 'Cost per Meal', 20, 'FoodCost Visualization'],
  ['overtime_control', 'financial_performance', 'Overtime Control', 20, 'Attendance & OT Early-Warning Dashboard'],
  ['inventory_accuracy', 'financial_performance', 'Inventory Accuracy', 20, 'MyFi Cost of Goods vs physical counts'],
  ['sanitation_cleanliness', 'quality_assurance', 'Sanitation & Cleanliness', 20, 'Safety Tracker / training reset → Ladle (future)'],
  ['hygiene_compliance', 'quality_assurance', 'Hygiene Compliance', 20, 'Safety Tracker / training reset'],
  ['ppe_compliance', 'quality_assurance', 'PPE Compliance', 20, 'Safety Tracker / training reset'],
  ['logs_completion', 'quality_assurance', 'Logs Completion', 20, 'Safety Tracker → Ladle (future)'],
  ['pic_required_trainings', 'quality_assurance', 'PIC / Required Trainings', 20, 'Food Safety Training Compliance'],
  ['attendance_reliability', 'employee_relations', 'Attendance / Reliability', 33.33, 'Track Path occurrence report'],
  ['training_development', 'employee_relations', 'Training & Development', 33.33, 'LMS Group Training Tracker'],
  ['engagement_retention', 'employee_relations', 'Engagement / Retention', 33.33, 'Visier'],
  ['guest_satisfaction_survey', 'customer_satisfaction', 'Guest Satisfaction Survey', 50, 'Student BITE'],
  ['service_recovery_complaints', 'customer_satisfaction', 'Service Recovery / Complaints', 50, 'Emails, comment cards'],
  ['waste_diversion_recycling', 'sustainability', 'Waste Diversion / Recycling', 33.33, 'Café Manager Waste-Not tab'],
  ['local_sustainable_sourcing', 'sustainability', 'Local / Sustainable Sourcing', 33.33, 'Café Manager Purchasing tab'],
  ['climate_change', 'sustainability', 'Climate Change', 33.33, 'Café Manager Climate Change'],
];

// --- deterministic generator (copied from lib/mock-scores.ts) ---
const clamp = (n) => Math.max(0, Math.min(3, n));
const round1 = (n) => Math.round(n * 10) / 10;
const HOUSE_BASE = { maseeh: 2.7, baker: 2.55, mccormick: 2.35, next: 2.05, simmons: 2.3, 'new-vassar': 1.85, retail: 2.5 };
const CAT_TILT = { nutrition_programming: 0.1, financial_performance: -0.1, quality_assurance: 0.15, employee_relations: -0.05, customer_satisfaction: 0.05, sustainability: -0.2 };
const HOUSE_TREND = { maseeh: 0.05, baker: -0.1, mccormick: 0.15, next: 0.1, simmons: -0.05, 'new-vassar': 0.2, retail: 0.0 };
const kpiWobble = (i) => ((i % 5) - 2) * 0.13;
const OVERRIDES = {
  P7: {
    'new-vassar': { sanitation_cleanliness: 1.1, logs_completion: 1.2, overtime_control: 1.3 },
    next: { overtime_control: 1.3, inventory_accuracy: 1.4 },
    simmons: { engagement_retention: 1.4 },
    mccormick: { climate_change: 1.3 },
  },
  P8: {
    'new-vassar': { sanitation_cleanliness: 1.4, logs_completion: 1.6, overtime_control: 1.5 },
    next: { overtime_control: 1.6, inventory_accuracy: 1.5 },
    simmons: { engagement_retention: 1.2 },
    baker: { food_cost_vs_budget: 1.4 },
  },
};
function genScore(slug, category, i, period) {
  const base = HOUSE_BASE[slug] ?? 2.2;
  const tilt = CAT_TILT[category] ?? 0;
  const drift = period === 'P8' ? HOUSE_TREND[slug] ?? 0 : 0;
  return clamp(base + tilt + kpiWobble(i) + drift);
}

const esc = (s) => String(s).replace(/'/g, "''");
const out = [];

out.push('-- Generated by scripts/gen-seed.mjs — demo data for Portfolio + House views.');
out.push('-- Idempotent: safe to re-run. Replace once the real scorecard xlsx pipeline lands.');
out.push('');

// Houses
out.push('insert into houses (slug, name, type, ec_name, contact, active) values');
out.push(
  HOUSES.map((h) => `  ('${h.slug}', '${esc(h.name)}', '${h.type}', 'TBD', 'TBD', true)`).join(',\n') +
    "\non conflict (slug) do update set name = excluded.name, type = excluded.type, active = true;"
);
out.push('');

// KPI definitions
out.push('insert into kpi_definitions (id, category, name, weight_pct, green_threshold, red_threshold, signal_source, measurement_mechanic) values');
out.push(
  KPIS.map(
    ([id, cat, name, w, src]) =>
      `  ('${id}', '${cat}', '${esc(name)}', ${w}, 2.5, 1.5, '${esc(src)}', '${esc(src)}')`
  ).join(',\n') +
    '\non conflict (id) do update set category = excluded.category, name = excluded.name, weight_pct = excluded.weight_pct, signal_source = excluded.signal_source, measurement_mechanic = excluded.measurement_mechanic;'
);
out.push('');

// Scorecard snapshots (P7 + P8)
const rows = [];
for (const period of ['P7', 'P8']) {
  for (const h of HOUSES) {
    KPIS.forEach(([id, cat, , w], i) => {
      const override = OVERRIDES[period]?.[h.slug]?.[id];
      const score = round1(override != null ? override : genScore(h.slug, cat, i, period));
      const weighted = Math.round(score * (w / 100) * 10000) / 10000;
      rows.push(`  ('${period}', '${h.slug}', '${id}', ${score}, ${weighted})`);
    });
  }
}
out.push('insert into scorecard_snapshots (period, house_id, kpi_id, score_0_3, weighted)');
out.push('select v.period, h.id, v.kpi_id, v.score, v.weighted');
out.push('from (values');
out.push(rows.join(',\n'));
out.push(') as v(period, slug, kpi_id, score, weighted)');
out.push('join houses h on h.slug = v.slug');
out.push('on conflict (period, house_id, kpi_id) do update set score_0_3 = excluded.score_0_3, weighted = excluded.weighted, captured_at = now();');
out.push('');

const sql = out.join('\n');
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.error(`Wrote supabase/seed.sql — ${HOUSES.length} houses, ${KPIS.length} KPIs, ${rows.length} snapshots`);
